Create test-7.js
daint2git/try-pull-request-slack-notifier pull request #9
Opened 2022-03-10 05:01 UTC by daint-1849

2022-03-10 05:02 UTC, daint-1849 commented
123

2022-03-10 05:37 UTC, daint-1849 reviewed
123

2022-03-10 06:48 UTC, daint-1849 commented
dai comment

2022-03-10 06:50 UTC, daint-1849 reviewed
ok

2022-03-10 12:11 UTC, daint-1849 commented
123

2022-03-10 12:12 UTC, daint-1849 reviewed
123

2022-03-10 12:14 UTC, daint2git commented on examples/test-7.js
> +console.log('Test 7');
123

2022-03-10 12:15 UTC, daint2git submitted a review, later dismissed
123

2022-03-10 12:16 UTC, daint-1849 reviewed
123123

2022-03-10 12:16 UTC, daint-1849 commented on examples/test-7.js
> +console.log('Test 7');
123

2022-03-10 12:17 UTC, daint2git requested changes

2022-03-10 12:17 UTC, daint2git commented on examples/test-7.js
> +console.log('Test 7');
123

2022-03-10 16:21 UTC, daint-1849 reviewed
123345

2022-03-10 16:23 UTC, daint2git approved these changes

2022-03-10 16:24 UTC, daint2git requested changes

2022-03-10 16:24 UTC, daint2git commented on examples/test-7.js
> +console.log('Test 7');
aaa

2022-03-10 16:59 UTC, daint-1849 reviewed
123

2022-03-10 16:59 UTC, daint2git requested changes
123

2022-03-10 17:06 UTC, daint-1849 commented
123

2022-03-10 17:12 UTC, daint-1849 reviewed
hihi

2022-03-10 17:31 UTC, daint-1849 commented
abc

2022-03-10 17:32 UTC, daint-1849 reviewed
123

2022-03-10 17:34 UTC, daint2git approved these changes

2022-03-11 16:21 UTC, daint2git commented
abc

2022-03-11 16:24 UTC, daint-1849 commented
123

2022-03-12 05:20 UTC, daint-1849 commented
123

2022-03-12 05:22 UTC, daint2git reviewed
123

2022-03-12 05:34 UTC, daint-1849 commented
ola ola

2022-03-12 05:36 UTC, daint2git commented on examples/test-7.js
> +console.log('Test 7');
mmmm

2022-03-12 05:38 UTC, daint2git approved these changes

2022-03-12 05:41 UTC, daint2git requested changes
on thong

2022-03-12 09:57 UTC, daint2git commented
123

2022-03-12 09:59 UTC, daint2git approved these changes

2022-03-12 10:00 UTC, merged